# This decsribes configurations of the ACU software, in terms of what
# datasets they make available.  Not so much interface configuration,
# i.e. ports and IP addresses.

platforms:
  satp:
    default_dataset: 'satp'
    datasets:
      - ['satp',       'DataSets.StatusSATPDetailed8100']
      - ['general',    'DataSets.StatusGeneral8100']
      - ['extra',      'DataSets.StatusExtra8100']
      - ['third',      'DataSets.Status3rdAxis']
      - ['faults',     'DataSets.StatusDetailedFaults']
      - ['pointing',   'DataSets.CmdPointingCorrection']
      - ['spem',       'DataSets.CmdSPEMParameter']
      - ['weather',    'DataSets.CmdWeatherStation']
      - ['azimuth',    'Antenna.SkyAxes.Azimuth']
      - ['elevation',  'Antenna.SkyAxes.Elevation']
