# Simple hacking script for reading .dat files generated by listen.py. Very slow for large files.`
# TODO: change lists to np arrays

import struct
import numpy as np

def data_to_lists(datafile):
    f = open(str(datafile), 'r')
    data = f.read()
    f.close()
    decoded_data = []
    for i in range(0,len(data),28):
        decode = struct.unpack('=iddd', data[i:i+28])
        decoded_data.append(decode)
    times = []; azs = []; els = []
    for i in decoded_data:
        times.append(i[1])
        azs.append(i[2])
        els.append(i[3])
    return times, azs, els	
	
