#!/usr/bin/expect

set PASSWORD [lindex $argv 3]
set DIRECTION [lindex $argv 2]
set NAME [lindex $argv 0]
set IP [lindex $argv 1]

log_user 0

spawn ssh $NAME@$IP
expect "password:" {send "$PASSWORD\r"}
expect "$ " {send "su -\r"}
expect ": " {send "$PASSWORD\r"}
expect "# " {send "cd /sys/class/gpio/gpio45\r"}
expect "# " {send "echo out > direction\r"}
expect "# " {send "echo $DIRECTION > value\r"}
expect "# " {send "exit\r"}
expect "$ " {send "exit\r"}
