read_len: 8 # update this to number of registers to query starting from 0
read_start: 1024
registers:
  0:
    max_val: 10000.0
    min_val: 0.0
    name: Oil pressure
    read_as: 16U
    scale: 1.0
    units: Kpa
  1:
    max_val: 200.0
    min_val: -50.0
    name: Coolant temperature
    read_as: 16S
    scale: 1.0
    units: Degrees C
  2:
    max_val: 200.0
    min_val: -50.0
    name: Oil temperature
    read_as: 16S
    scale: 1.0
    units: Degrees C
  3:
    max_val: 130.0
    min_val: 0.0
    name: Fuel level
    read_as: 16U
    scale: 1.0
    units: '%'
  4:
    max_val: 40.0
    min_val: 0.0
    name: Charge alternator voltage
    read_as: 16U
    scale: 0.1
    units: V
  5:
    max_val: 40.0
    min_val: 0.0
    name: Engine Battery voltage
    read_as: 16U
    scale: 0.1
    units: V
  6:
    max_val: 6000.0
    min_val: 0.0
    name: Engine speed
    read_as: 16U
    scale: 1.0
    units: RPM
  7:
    max_val: 70.0
    min_val: 0.0
    name: Generator frequency
    read_as: 16U
    scale: 0.1
    units: Hz
  8:
    max_val: 18000.0
    min_val: 0.0
    name: Generator L1-N voltage
    read_as: 32U
    scale: 0.1
    units: V
  10:
    max_val: 18000.0
    min_val: 0.0
    name: Generator L2-N voltage
    read_as: 32U
    scale: 0.1
    units: V
  12:
    max_val: 18000.0
    min_val: 0.0
    name: Generator L3-N voltage
    read_as: 32U
    scale: 0.1
    units: V
  14:
    max_val: 30000.0
    min_val: 0.0
    name: Generator L1-L2 voltage
    read_as: 32U
    scale: 0.1
    units: V
  16:
    max_val: 30000.0
    min_val: 0.0
    name: Generator L2-L3 voltage
    read_as: 32U
    scale: 0.1
    units: V
  18:
    max_val: 30000.0
    min_val: 0.0
    name: Generator L3-L1 voltage
    read_as: 32U
    scale: 0.1
    units: V
  20:
    max_val: 99999.9
    min_val: 0.0
    name: Generator L1 current
    read_as: 32U
    scale: 0.1
    units: A
  22:
    max_val: 99999.9
    min_val: 0.0
    name: Generator L2 current
    read_as: 32U
    scale: 0.1
    units: A
  24:
    max_val: 99999.9
    min_val: 0.0
    name: Generator L3 current
    read_as: 32U
    scale: 0.1
    units: A
  26:
    max_val: 99999.9
    min_val: 0.0
    name: Generator earth current
    read_as: 32U
    scale: 0.1
    units: A
  28:
    max_val: 99999999.0
    min_val: -99999999.0
    name: Generator L1 watts
    read_as: 32S
    scale: 1.0
    units: W
  30:
    max_val: 99999999.0
    min_val: -99999999.0
    name: Generator L2 watts
    read_as: 32S
    scale: 1.0
    units: W
  32:
    max_val: 99999999.0
    min_val: -99999999.0
    name: Generator L3 watts
    read_as: 32S
    scale: 1.0
    units: W
  34:
    max_val: 180.0
    min_val: -180.0
    name: Generator current lag/lead
    read_as: 16S
    scale: 1.0
    units: degrees
  35:
    max_val: 70.0
    min_val: 0.0
    name: Mains frequency
    read_as: 16U
    scale: 0.1
    units: Hz
  36:
    max_val: 18000.0
    min_val: 0.0
    name: Mains L1-N voltage
    read_as: 32U
    scale: 0.1
    units: V
  38:
    max_val: 18000.0
    min_val: 0.0
    name: Mains L2-N voltage
    read_as: 32U
    scale: 0.1
    units: V
  40:
    max_val: 18000.0
    min_val: 0.0
    name: Mains L3-N voltage
    read_as: 32U
    scale: 0.1
    units: V
  42:
    max_val: 30000.0
    min_val: 0.0
    name: Mains L1-L2 voltage
    read_as: 32U
    scale: 0.1
    units: V
  44:
    max_val: 30000.0
    min_val: 0.0
    name: Mains L2-L3 voltage
    read_as: 32U
    scale: 0.1
    units: V
  46:
    max_val: 30000.0
    min_val: 0.0
    name: Mains L3-L1 voltage
    read_as: 32U
    scale: 0.1
    units: V
  48:
    max_val: 180.0
    min_val: -180.0
    name: Mains voltage phase lag/lead
    read_as: 16S
    scale: 1.0
    units: degrees
  49:
    max_val: 3.0
    min_val: 0.0
    name: Generator phase rotation
    read_as: 16U
    scale: 1.0
    units: ''
  50:
    max_val: 3.0
    min_val: 0.0
    name: Mains phase rotation
    read_as: 16U
    scale: 1.0
    units: ''
  51:
    max_val: 180.0
    min_val: -180.0
    name: Mains current lag/lead
    read_as: 16S
    scale: 1.0
    units: degrees
  52:
    max_val: 99999.9
    min_val: 0.0
    name: Mains L1 current
    read_as: 32U
    scale: 0.1
    units: A
  54:
    max_val: 99999.9
    min_val: 0.0
    name: Mains L2 current
    read_as: 32U
    scale: 0.1
    units: A
  56:
    max_val: 99999.9
    min_val: 0.0
    name: Mains L3 current
    read_as: 32U
    scale: 0.1
    units: A
  58:
    max_val: 99999.9
    min_val: 0.0
    name: Mains earth current
    read_as: 32U
    scale: 0.1
    units: A
  60:
    max_val: 99999999.0
    min_val: -99999999.0
    name: Mains L1 watts
    read_as: 32S
    scale: 1.0
    units: W
  62:
    max_val: 99999999.0
    min_val: -99999999.0
    name: Mains L2 watts
    read_as: 32S
    scale: 1.0
    units: W
  64:
    max_val: 99999999.0
    min_val: -99999999.0
    name: Mains L3 watts
    read_as: 32S
    scale: 1.0
    units: W
  66:
    max_val: 180.0
    min_val: -180.0
    name: Bus current lag/lead
    read_as: 16S
    scale: 1.0
    units: degrees
  67:
    max_val: 70.0
    min_val: 0.0
    name: Bus frequency
    read_as: 16U
    scale: 0.1
    units: Hz
  68:
    max_val: 18000.0
    min_val: 0.0
    name: Bus L1-N voltage
    read_as: 32U
    scale: 0.1
    units: V
  70:
    max_val: 18000.0
    min_val: 0.0
    name: Bus L2-N voltage
    read_as: 32U
    scale: 0.1
    units: V
  72:
    max_val: 18000.0
    min_val: 0.0
    name: Bus L3-N voltage
    read_as: 32U
    scale: 0.1
    units: V
  74:
    max_val: 30000.0
    min_val: 0.0
    name: Bus L1-L2 voltage
    read_as: 32U
    scale: 0.1
    units: V
  76:
    max_val: 30000.0
    min_val: 0.0
    name: Bus L2-L3 voltage
    read_as: 32U
    scale: 0.1
    units: V
  78:
    max_val: 30000.0
    min_val: 0.0
    name: Bus L3-L1 voltage
    read_as: 32U
    scale: 0.1
    units: V
  80:
    max_val: 99999.9
    min_val: 0.0
    name: Bus L1 current
    read_as: 32U
    scale: 0.1
    units: A
  82:
    max_val: 99999.9
    min_val: 0.0
    name: Bus L2 current
    read_as: 32U
    scale: 0.1
    units: A
  84:
    max_val: 99999.9
    min_val: 0.0
    name: Bus L3 current
    read_as: 32U
    scale: 0.1
    units: A
  86:
    max_val: 99999.9
    min_val: 0.0
    name: Bus earth current
    read_as: 32U
    scale: 0.1
    units: A
  88:
    max_val: 999999999.0
    min_val: -999999999.0
    name: Bus L1 watts
    read_as: 32S
    scale: 1.0
    units: W
  90:
    max_val: 999999999.0
    min_val: -999999999.0
    name: Bus L2 watts
    read_as: 32S
    scale: 1.0
    units: W
  92:
    max_val: 999999999.0
    min_val: -999999999.0
    name: Bus L3 watts
    read_as: 32S
    scale: 1.0
    units: W
  94:
    max_val: 3.0
    min_val: 0.0
    name: Bus phase rotation
    read_as: 16U
    scale: 1.0
    units: ''
string_name: Engine Data
