cameras:
  - address: '192.168.xx.xx'
    location: 'highbay_cargo'
    resolution: 'N640x480,100'
    user: 'user'
    password: 'password'
    brand: 'acti'

  - address: '192.168.xx.xx'
    location: 'satp1'
    user: 'user'
    password: 'password'
    brand: 'reolink'
