# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath('..'))
from socs import __version__ as socs_version

# -- Project information -----------------------------------------------------

project = 'SOCS'
copyright = '2018-2019, Simons Observatory DAQ Group'
author = 'Simons Observatory DAQ Group'

# The short X.Y version.
version = socs_version
# The full version, including alpha/beta/rc tags.
release = socs_version


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
]
extensions += ['sphinxarg.ext']

# Present auto-documented members in source order (rather than alphabetical).
autodoc_default_options = {
    'member-order': 'bysource',
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# Force import protection
os.environ['READTHEDOCS'] = 'True'

autodoc_mock_imports = ['spt3g',
                        'so3g',
                        'so3g.proj',
                        'labjack',
                        'labjack.ljm',
                        'labjack.ljm.ljm',
                        'ocs',
                        'ocs.agent',
                        'ocs.client_http',
                        'ocs.ocs_twisted',
                        'ocs.ocs_agent',
                        'ocs.ocs_client',
                        'ocs.agent.aggregator',
                        'xy_agent',
                        'xy_agent.xy_connect',
                        'soaculib',
                        'scan_helpers',
                        'soaculib.twisted_backend',
                        'soaculib.status_keys',
                        'pfeiffer_vacuum_protocol',
                        'pfeiffer_vacuum_protocol.pfeiffer_vacuum_protocol',
                        'pfeiffer_tc400_driver',
                        'sodetlib',
                        'sodetlib.operations',
                        'sodetlib.det_config',
                        'src',
                        'src.pid_controller',
                        'cv2',
                        'imutils',
                        ]
from unittest import mock

for m in autodoc_mock_imports:
    sys.modules[m] = mock.Mock()

# Mock the ocs_agent.param decorator to preserve docstrings
def wrap(*args, **kw):
    return lambda f: f

import ocs

ocs.ocs_agent.param = wrap

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = [
    'theme_overrides.css',  # override wide tables in RTD theme
]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'SOCSdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'SOCS.tex', 'SOCS Documentation',
     'Simons Observatory DAQ Group', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'socs', 'SOCS Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'SOCS', 'SOCS Documentation',
     author, 'SOCS', 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
