name: Build Official Docker Images

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    # (start steps from pytest workflow)
    # Install
    - name: clone ocs
      uses: actions/checkout@v2
      with:
        repository: 'simonsobs/ocs'

    - name: Install ocs
      run: |
        pip3 install -r requirements.txt
        pip3 install .

    # Fetch all history for all tags and branches
    - name: clone socs
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install socs
      run: |
        pip3 install -r requirements.txt
        pip3 install -e .

    # Unit Tests
    - name: Run unit tests
      working-directory: ./tests
      run: |
        COVERAGE_FILE=.coverage.unit python3 -m pytest --cov -m 'not (integtest or spt3g)'

    - name: Build docker test images
      run: |
        docker-compose build socs

    - name: Test with spt3g dependent tests wtihin a docker container
      run: |
        docker run -v $PWD:/coverage --rm -w="/app/socs/tests/" socs sh -c "COVERAGE_FILE=/coverage/.coverage.docker python3 -m pytest --cov -m 'spt3g'"

    # Integration Tests
    - name: Build images for integration tests
      run: |
        docker-compose build ocs-lakeshore372-simulator

    - name: Run integration tests
      working-directory: ./tests
      run: |
        COVERAGE_FILE=.coverage.int python3 -m pytest --cov -m 'integtest'

    # Coverage
    - name: Report test coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mv ./tests/.coverage.* ./
        pip install coveralls
        coverage combine
        coverage report
        coveralls --service=github
    # (end steps from pytest workflow)

    # Build
    - name: Build docker images
      run: |
        docker-compose build

    # Dockerize
    - name: Build and push official docker image
      env:
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
        DOCKERHUB_ORG: "simonsobs"
      run: |
        export DOCKER_TAG=`git describe --tags --always`
        echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin;

        # Tag all images for upload to the registry
        docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} docker tag {}:latest ${DOCKERHUB_ORG}/{}:latest
        docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} docker tag {}:latest ${DOCKERHUB_ORG}/{}:${DOCKER_TAG}

        # Upload to docker registry
        docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} docker push ${DOCKERHUB_ORG}/{}:latest
        docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} docker push ${DOCKERHUB_ORG}/{}:${DOCKER_TAG}
        docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} echo ${DOCKERHUB_ORG}/{}:${DOCKER_TAG} pushed
