name: Run Tests

on:
  pull_request:
    paths:
      - 'docs/**'
      - '**.rst'
      - '**.md'
      - '.flake8'
      - '.pre-commit-config.yaml'
      - '.readthedocs.yaml'
      - '.github/dependabot.yml'

jobs:
  test:
    name: pytest with coverage
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No build required" '
