name: Run Tests

on:
  pull_request:
    paths:
      - 'docs/**'
      - '*.rst'
      - '*.md'

jobs:
  test:
    name: pytest with coverage
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No build required" '
