name: Test Docker Build

on:
  pull_request:
    paths:
      - 'docs/**'
      - '*.rst'
      - '*.md'

jobs:
  build:
    name: test image build
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No build required" '
